[package]
name = "git-global"
version = "0.1.0"
authors = ["Eric Petersen <eric@huskers.unl.edu>"]

[[bin]]
name = "git-global"
doc = false

[dependencies]
clap = "2"
walkdir = "1"

[dependencies.git2]
version = "0.6"
default-features = false  # don't want SSH/HTTPS/Curl
